parameters:
- name: zolaVersion
  default: '0.18.0'
  type: string

jobs:

- job: build
  pool:
    vmImage: ubuntu-latest
  steps:

  - bash: |
      curl -fsSL \
        'https://github.com/getzola/zola/releases/download/v${{ parameters.zolaVersion }}/zola-v${{ parameters.zolaVersion }}-x86_64-unknown-linux-gnu.tar.gz' \
      | tar zx
    displayName: "Install Zola ${{ parameters.zolaVersion }}"

  - bash: ./zola build -o $(build.artifactStagingDirectory) --force
    displayName: "Build with Zola"

  - task: PublishPipelineArtifact@0
    displayName: Publish built site as artifact
    inputs:
      artifactName: website
      targetPath: $(build.artifactStagingDirectory)
