parameters:
- name: zolaVersion
  default: '0.18.0'
  type: string

jobs:

- job: build
  pool:
    vmImage: ubuntu-latest
  steps:

  - bash: |
      curl -fsSL \
        'https://https://github.com/getzola/zola/releases/download/v${{ parameters.zolaVersion }}/zola-v${{ parameters.zolaVersion }}-x86_64-unknown-linux-gnu.tar.gz' \
        | tar zx
    displayName: "Install Zola ${{ parameters.zolaVersion }}"

  - bash: ./zola build
    displayName: "Build with Zola"
