trigger:
  branches:
    include:
    - main

stages:
- stage: Build
  jobs:
  - template: azure-build.yml

- stage: Deploy
  condition: and(succeeded('Build'), ne(variables['build.reason'], 'PullRequest'))
  jobs:
  - template: azure-deploy.yml
