trigger:
  branches:
    include:
    - main

stages:
- stage: Prep
  jobs:
  - template: azure-prep.yml

- stage: Build
  condition: succeeded('Prep')
  jobs:
  - template: azure-build.yml

- stage: Summarize
  condition: succeeded('Build')
  jobs:
  - template: azure-summarize.yml

- stage: Deploy
  condition: and(succeeded('Summarize'), ne(variables['build.reason'], 'PullRequest'))
  jobs:
  - template: azure-deploy.yml
