
jobs:

- job: upload
  pool:
    vmImage: ubuntu-latest
  steps:

  - download: current

  - checkout: self

  - task: DownloadSecureFile@1
    name: sshKey
    displayName: 'Download SSH key'
    inputs:
      secureFile: 'websitecd_ed25519'

  # This doesn't really need to be a secure file, but as long as we're using the
  # infrastructure ...
  - task: DownloadSecureFile@1
    name: knownHost
    displayName: 'Download known-hosts data'
    inputs:
      secureFile: 'newtoncx_knownhost.txt'

  # Ditto.
  - task: DownloadSecureFile@1
    name: sshConfig
    displayName: 'Download ssh_config data'
    inputs:
      secureFile: 'newtoncx_sshconfig.txt'

  # Surprisingly, it seems that the "secure files" are not given restrictive
  # filesystem permissions upon creation.
  - bash: |
      mkdir -p $HOME/.ssh
      cat $(knownHost.secureFilePath) >>$HOME/.ssh/known_hosts
      cp -p $(sshConfig.secureFilePath) $HOME/.ssh/config
      chmod 400 $HOME/.ssh/config $(sshKey.secureFilePath)
    displayName: Set up SSH for newton.cx

  - bash: rsync -e 'ssh -i $(sshKey.secureFilePath)' -avP $(pipeline.workspace)/website/ newton.cx:zztest/
    displayName: rsync content
