
jobs:

- job: upload
  pool:
    vmImage: ubuntu-latest
  steps:

  - download: current

  - checkout: self

  - task: DownloadSecureFile@1
    name: sshKey
    displayName: 'Download SSH key'
    inputs:
      secureFile: 'websitecd_ed25519'

  - bash: rsync -e 'ssh -i $(sshKey.secureFilePath) -p 2222' -avP $(pipeline.workspace)/website/ newton.cx:zztest/
    displayName: rsync content
